"""empty message

Revision ID: 493e68cb3a28
Revises: b37e131d6b20
Create Date: 2021-04-15 22:39:25.867341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '493e68cb3a28'
down_revision = 'b37e131d6b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'mass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('mass', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
