"""empty message

Revision ID: b37e131d6b20
Revises: 90231305f659
Create Date: 2021-04-14 02:17:11.049784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b37e131d6b20'
down_revision = '90231305f659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('rotation', sa.Integer(), nullable=True))
    op.drop_column('planets', 'rotation_period')
    op.drop_column('planets', 'diameter')
    op.drop_column('planets', 'orbital_period')
    op.drop_column('planets', 'surface_water')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('surface_water', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planets', sa.Column('orbital_period', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planets', sa.Column('diameter', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planets', sa.Column('rotation_period', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('planets', 'rotation')
    # ### end Alembic commands ###
